## I'm a Jupyter Notebook 

#### You can:

* Execute cells
* Use PyCharm smart code editing inside Jupyter Notebook
* Use Jupyter execution features inside PyCharm
* Use Variables View
* Debug cells


In [2]:

my_name = "Earth"
earth_neighbors = ["Mars", "Venus"]
print("Hello from Earth!")


Hello from Earth!



### Let's send greetings


In [3]:

def greet_neighbors(neighbors):
    for n in neighbors:
        print(f"Hi {n}!")
    return len(neighbors)

num = greet_neighbors(earth_neighbors)
print(num)
print(f"I have {num} neighbors")


Hi Mars!
Hi Venus!
2
I have 2 neighbors


In [4]:

jupiter_neighbors = ["Mars", "Saturn"]
jupiter_len = greet_neighbors(jupiter_neighbors)
print(jupiter_len)


Hi Mars!
Hi Saturn!
2


In [7]:

import numpy as np
from ds.decision_tree import get_features_targets

data = np.load('../data/sdss_galaxy_colors.npy')

features, targets = get_features_targets(data)

print(features)


[0.539301   0.1645703  0.04190006 0.04427702]
[[3.14760e-01 5.71000e-02 2.89910e-01 7.19200e-02]
 [1.20020e+00 8.20260e-01 4.52940e-01 2.46650e-01]
 [1.65941e+00 8.34990e-01 4.04820e-01 3.12660e-01]
 ...
 [1.72629e+00 9.39050e-01 5.81730e-01 3.82050e-01]
 [2.32870e-01 1.82550e-01 2.93910e-01 1.84400e-02]
 [1.90670e-01 3.65500e-02 4.63900e-02 2.30000e-04]]
